// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtydzvhHxYDXW7et8bAiDs4tok261db0g',
    appId: '1:529843325868:web:ab0281fa5ba892c8e44809',
    messagingSenderId: '529843325868',
    projectId: 'facebook-clone-ab67f',
    authDomain: 'facebook-clone-ab67f.firebaseapp.com',
    storageBucket: 'facebook-clone-ab67f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2YYEiJvAYfFe0KTQjPtj4UPWihcVcEpA',
    appId: '1:529843325868:android:b03b550ebd10dfcbe44809',
    messagingSenderId: '529843325868',
    projectId: 'facebook-clone-ab67f',
    storageBucket: 'facebook-clone-ab67f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjlvdQxB3RQ32OV7pxP883IrhLjRpvBTw',
    appId: '1:529843325868:ios:e85d7002150fa7c4e44809',
    messagingSenderId: '529843325868',
    projectId: 'facebook-clone-ab67f',
    storageBucket: 'facebook-clone-ab67f.firebasestorage.app',
    iosBundleId: 'com.example.hoslaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjlvdQxB3RQ32OV7pxP883IrhLjRpvBTw',
    appId: '1:529843325868:ios:e85d7002150fa7c4e44809',
    messagingSenderId: '529843325868',
    projectId: 'facebook-clone-ab67f',
    storageBucket: 'facebook-clone-ab67f.firebasestorage.app',
    iosBundleId: 'com.example.hoslaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtydzvhHxYDXW7et8bAiDs4tok261db0g',
    appId: '1:529843325868:web:81ef936147af5678e44809',
    messagingSenderId: '529843325868',
    projectId: 'facebook-clone-ab67f',
    authDomain: 'facebook-clone-ab67f.firebaseapp.com',
    storageBucket: 'facebook-clone-ab67f.firebasestorage.app',
  );
}
